[graph]
all-features = true

[advisories]
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []

[licenses]
allow = [
    "0BSD",
    "Apache-2.0",
    "bzip2-1.0.6",
    "CDLA-Permissive-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
