//! Local publication: atomically publish one eagerly populated stage, or remove one target.
//!
//! Owns the exact single-target effect law: a native no-replace rename commit boundary and direct
//! idempotent target removal. It never republishes, follows
//! links, claims ownership, or retries. Evidence is adapter-attested effect data, not an
//! authorization. Feature-gated on `local`.
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use super::{LocalError, LocalSource, LocalTarget, StagePlacement, StagedTree};

#[derive(Clone, Debug, Eq, PartialEq)]
/// Materialized file, directory, and byte totals published with one staged tree.
pub struct ApplyEvidence {
    /// The files value.
    pub files: usize,
    /// The directories value.
    pub directories: usize,
    /// The bytes value.
    pub bytes: u64,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
/// Whether direct target removal changed the filesystem.
pub enum RemoveEvidence {
    /// The removed outcome.
    Removed,
    /// The unchanged outcome.
    Unchanged,
}

pub(crate) fn stage(target: &Path) -> Result<StagedTree, LocalError> {
    let parent = target_parent(target)?;
    fs::create_dir_all(parent)
        .map_err(|error| LocalError::io("create stage parent", parent, error))?;
    let parent = parent
        .canonicalize()
        .map_err(|error| LocalError::io("canonicalize stage parent", parent, error))?;
    let workspace = tempfile::Builder::new()
        .prefix(".pulith-stage-")
        .tempdir_in(&parent)
        .map_err(|error| LocalError::io("create staged tree", &parent, error))?;
    let root = workspace.path().join("tree");
    Ok(StagedTree::destination(workspace, root, parent))
}

impl StagedTree {
    /// Writes generated bytes into this private stage without exposing a partial target.
    pub fn write_file(
        self,
        bytes: impl AsRef<[u8]>,
        destination: impl Into<PathBuf>,
    ) -> Result<Self, LocalError> {
        use std::io::Write;
        let destination = stage_destination(&self.root, destination.into())?;
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| LocalError::io("create stage file parent", parent, error))?;
        }
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&destination)
            .map_err(|error| LocalError::io("create generated stage file", &destination, error))?;
        file.write_all(bytes.as_ref())
            .map_err(|error| LocalError::io("write generated stage file", &destination, error))?;
        Ok(self)
    }

    /// Copies one admitted regular file into a contained path in this private stage.
    pub fn copy_file(
        self,
        source: LocalSource,
        destination: impl Into<PathBuf>,
    ) -> Result<Self, LocalError> {
        let destination = stage_destination(&self.root, destination.into())?;
        let source = source.0;
        let metadata = fs::symlink_metadata(&source)
            .map_err(|error| LocalError::io("inspect stage file source", &source, error))?;
        if !metadata.file_type().is_file() {
            return Err(LocalError::UnsupportedLocalEntry(source));
        }
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| LocalError::io("create stage file parent", parent, error))?;
        }
        fs::copy(&source, &destination)
            .map_err(|error| LocalError::io("copy file into stage", &source, error))?;
        Ok(self)
    }

    /// Recursively copies one admitted directory tree into a contained stage path.
    pub fn copy_tree(
        self,
        source: LocalSource,
        destination: impl Into<PathBuf>,
    ) -> Result<Self, LocalError> {
        let destination = stage_destination(&self.root, destination.into())?;
        let source = source.0;
        let metadata = fs::symlink_metadata(&source)
            .map_err(|error| LocalError::io("inspect stage tree source", &source, error))?;
        if !metadata.file_type().is_dir() {
            return Err(LocalError::UnsupportedLocalEntry(source));
        }
        copy_directory_to_stage(&source, &destination)?;
        Ok(self)
    }

    /// Atomically publishes this complete stage only when the target is absent.
    pub fn publish(self, target: LocalTarget) -> Result<ApplyEvidence, LocalError> {
        let target_path = target.0;
        let target_parent = target_parent(&target_path)?
            .canonicalize()
            .map_err(|error| LocalError::io("canonicalize publish parent", &target_path, error))?;

        let StagedTree {
            workspace,
            root,
            placement,
        } = self;
        if matches!(&placement, StagePlacement::Destination(parent) if parent == &target_parent) {
            let stats = inspect_regular_tree(&root)?;
            rename_no_replace(&root, &target_path)?;
            drop(workspace);
            return Ok(ApplyEvidence {
                files: stats.files,
                directories: stats.directories,
                bytes: stats.bytes,
            });
        }

        let destination = stage(&target_path)?;
        let destination = if fs::symlink_metadata(&root)
            .map_err(|error| LocalError::io("inspect staged root", &root, error))?
            .file_type()
            .is_dir()
        {
            destination.copy_tree(LocalSource(root), PathBuf::new())?
        } else {
            destination.copy_file(LocalSource(root), PathBuf::new())?
        };
        drop(workspace);
        destination.publish(LocalTarget(target_path))
    }
}

fn stage_destination(root: &Path, relative: PathBuf) -> Result<PathBuf, LocalError> {
    use std::path::Component;
    if !relative.as_os_str().is_empty()
        && (relative.is_absolute()
            || relative
                .components()
                .any(|component| !matches!(component, Component::Normal(_))))
    {
        return Err(LocalError::InvalidStagePath(relative));
    }
    Ok(if relative.as_os_str().is_empty() {
        root.to_path_buf()
    } else {
        root.join(relative)
    })
}

#[derive(Clone, Copy, Default)]
struct TreeStats {
    files: usize,
    directories: usize,
    bytes: u64,
}

enum RegularEntry {
    File,
    Directory,
}

impl RegularEntry {
    fn admit(entry: &walkdir::DirEntry) -> Result<Self, LocalError> {
        let kind = entry.file_type();
        if !kind.is_symlink() && !is_reparse(entry)? {
            if kind.is_file() {
                return Ok(Self::File);
            }
            if kind.is_dir() {
                return Ok(Self::Directory);
            }
        }
        Err(LocalError::UnsupportedLocalEntry(entry.path().into()))
    }
}

#[cfg(not(windows))]
fn is_reparse(_: &walkdir::DirEntry) -> Result<bool, LocalError> {
    Ok(false)
}

#[cfg(windows)]
fn is_reparse(entry: &walkdir::DirEntry) -> Result<bool, LocalError> {
    use std::os::windows::fs::MetadataExt;
    use windows_sys::Win32::Storage::FileSystem::FILE_ATTRIBUTE_REPARSE_POINT;
    let metadata = entry.metadata().map_err(|error| {
        LocalError::io(
            "inspect staged entry",
            entry.path(),
            io::Error::other(error),
        )
    })?;
    Ok(metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0)
}

fn walk_error(action: &'static str, root: &Path, error: walkdir::Error) -> LocalError {
    let path = error.path().unwrap_or(root).to_path_buf();
    LocalError::io(action, path, io::Error::other(error))
}

fn inspect_regular_tree(root: &Path) -> Result<TreeStats, LocalError> {
    let metadata = fs::symlink_metadata(root)
        .map_err(|error| LocalError::io("inspect staged root", root, error))?;
    if metadata.file_type().is_file() {
        return Ok(TreeStats {
            files: 1,
            directories: 0,
            bytes: metadata.len(),
        });
    }
    if !metadata.file_type().is_dir() {
        return Err(LocalError::UnsupportedLocalEntry(root.to_path_buf()));
    }
    let mut stats = TreeStats::default();
    for entry in walkdir::WalkDir::new(root).follow_links(false) {
        let entry = entry.map_err(|error| walk_error("walk staged tree", root, error))?;
        match RegularEntry::admit(&entry)? {
            RegularEntry::Directory => stats.directories += 1,
            RegularEntry::File => {
                stats.files += 1;
                stats.bytes += entry
                    .metadata()
                    .map_err(|error| {
                        LocalError::io(
                            "inspect staged file",
                            entry.path(),
                            io::Error::other(error.to_string()),
                        )
                    })?
                    .len();
            }
        }
    }
    Ok(stats)
}

#[cfg(unix)]
fn rename_no_replace(source: &Path, target: &Path) -> Result<(), LocalError> {
    use rustix::fs::{CWD, RenameFlags, renameat_with};
    use rustix::io::Errno;
    renameat_with(CWD, source, CWD, target, RenameFlags::NOREPLACE).map_err(|error| {
        if matches!(error, Errno::EXIST | Errno::NOTEMPTY) {
            LocalError::AlreadyPublished(target.to_path_buf())
        } else if matches!(error, Errno::NOSYS | Errno::OPNOTSUPP) {
            LocalError::PublishUnavailable {
                path: target.to_path_buf(),
                source: io::Error::from(error),
            }
        } else {
            LocalError::io("publish staged tree", target, io::Error::from(error))
        }
    })
}

#[cfg(windows)]
fn rename_no_replace(source: &Path, target: &Path) -> Result<(), LocalError> {
    use std::os::windows::ffi::OsStrExt;
    use windows_sys::Win32::Foundation::{ERROR_ALREADY_EXISTS, ERROR_FILE_EXISTS};
    let source: Vec<u16> = source.as_os_str().encode_wide().chain(Some(0)).collect();
    let target_wide: Vec<u16> = target.as_os_str().encode_wide().chain(Some(0)).collect();
    // SAFETY: both buffers are NUL-terminated and live for the duration of the call.
    let moved = unsafe {
        windows_sys::Win32::Storage::FileSystem::MoveFileExW(
            source.as_ptr(),
            target_wide.as_ptr(),
            0,
        )
    };
    if moved != 0 {
        Ok(())
    } else {
        let error = io::Error::last_os_error();
        if matches!(
            error.raw_os_error().map(|code| code as u32),
            Some(ERROR_ALREADY_EXISTS) | Some(ERROR_FILE_EXISTS)
        ) {
            Err(LocalError::AlreadyPublished(target.to_path_buf()))
        } else {
            Err(LocalError::io("publish staged tree", target, error))
        }
    }
}
/// Remove one exact local target directly (no source, no verification, no ownership claim).
impl crate::Remove for crate::local::LocalTarget {
    type Error = LocalError;
    type Output = RemoveEvidence;

    fn remove(self) -> Result<Self::Output, Self::Error> {
        let target = self.as_path();
        match remove_existing(target) {
            Ok(()) => Ok(RemoveEvidence::Removed),
            Err(LocalError::Io { source, .. }) if source.kind() == io::ErrorKind::NotFound => {
                Ok(RemoveEvidence::Unchanged)
            }
            Err(error) => Err(error),
        }
    }
}

fn copy_directory_to_stage(source: &Path, stage: &Path) -> Result<(), LocalError> {
    for entry in walkdir::WalkDir::new(source).follow_links(false) {
        let entry = entry.map_err(|error| walk_error("walk source directory", source, error))?;
        let relative = entry.path().strip_prefix(source).map_err(|err| {
            LocalError::io(
                "strip source prefix",
                entry.path(),
                io::Error::other(err.to_string()),
            )
        })?;
        if relative.as_os_str().is_empty() {
            continue;
        }

        let destination = stage.join(relative);
        match RegularEntry::admit(&entry)? {
            RegularEntry::Directory => {
                fs::create_dir_all(&destination)
                    .map_err(|err| LocalError::io("create staged directory", &destination, err))?;
            }
            RegularEntry::File => {
                if let Some(parent) = destination.parent() {
                    fs::create_dir_all(parent)
                        .map_err(|err| LocalError::io("create staged file parent", parent, err))?;
                }
                fs::copy(entry.path(), &destination).map_err(|err| {
                    LocalError::io("copy file to staged directory", &destination, err)
                })?;
            }
        }
    }

    Ok(())
}

fn remove_existing(path: &Path) -> Result<(), LocalError> {
    let metadata = fs::symlink_metadata(path)
        .map_err(|err| LocalError::io("read target metadata", path, err))?;
    if metadata.file_type().is_dir() && !metadata.file_type().is_symlink() {
        fs::remove_dir_all(path).map_err(|err| LocalError::io("remove directory", path, err))
    } else {
        fs::remove_file(path).map_err(|err| LocalError::io("remove file", path, err))
    }
}

fn target_parent(target: &Path) -> Result<&Path, LocalError> {
    target
        .parent()
        .filter(|path| !path.as_os_str().is_empty())
        .ok_or_else(|| {
            LocalError::InvalidPreparation(format!(
                "target path must have a parent directory: {}",
                target.display()
            ))
        })
}
